### ISSUE TITLE
hbsd migration version error

### ISSUE THREAD

**Issue by FlorianHeigl** [xmj/xmj.github.io#1]
Hi, just fyi, I had to go back to a feb 2017 version of hbsd-update to work with the migration doc. on my last try about a month ago it had 'just worked' so it's some new feature of hbsd-update that causes this.
Not yet sure if i'm going to be able to get through the migration again, but you're warned now :)

**Comment by xmj** [comment]
Without knowing the exact error message figuring out what's wrong will be quite a task. Do you recall what it failed on?

**Comment by xmj** [comment]
Thank you for your report.
I'm closing this due to lack of feedback or guides how to reproduce. 

Do feel free to re-open it in case you run into this again in the future, and attach logfiles/error messages/anything to help debugging it.
